### ISSUE TITLE
Шаблони для сторінок (Візуал)

### ISSUE THREAD

**Issue by AlexanderZero435** [TNTU-121-Software-Engineering/SE-42_2022.github.io#12]
**Створити візуальні шаблони для сторінок**

**Comment by AlexanderZero435** [comment]
> - [ ] “Про наc”
> - [ ] “Умови та терміни”
> - [ ] “Список товарів”
> - [ ] “Новини”
> - [ ] “Блог”
> - [ ] “Контакти”

**Comment by AlexanderZero435** [comment]
![ABOUT](https://user-images.githubusercontent.com/58272989/203558450-9992eabc-33e1-4910-9ac3-5f0f8db7d119.png)
![BLOG](https://user-images.githubusercontent.com/58272989/203558453-6dc76787-3de2-4639-a70b-80d3035c744c.png)
![CONTACTS](https://user-images.githubusercontent.com/58272989/203558457-f71cefcc-4915-45bd-8769-7414297749e9.png)
![NEWS](https://user-images.githubusercontent.com/58272989/203558462-e0495590-5919-4b7f-a8a7-b58afaab7449.png)
![PRODUCT LIST](https://user-images.githubusercontent.com/58272989/203558463-0ea34c50-c9aa-47c3-bc9d-90a4d50b32af.png)

**Comment by KaiserElindai** [comment]
Сторінку "Умови та терміни" слід об'єднати з сторінкою "Про нас"

**Comment by AlexanderZero435** [comment]
> Сторінку "Умови та терміни" слід об'єднати з сторінкою "Про нас"

Використаємо область призначену для опису проекту на сторінці "Про нас".
