### ISSUE TITLE
Необхідні дослідження

### ISSUE THREAD

**Issue by AndreDElric** [TNTU-121-Software-Engineering/SE-42_2022.github.io#9]
**ДИЗАЙН САЙТУ:**

> - [x] Дослідити тенденції в плані дизайну сайтів по маркетингу меблів
> - [x] Визначити кольорову гамму
> - [x] CSS для анімації

ФУНКЦІОНАЛЬНІ ЮНІТИ:

> - [x] Інтеграція відео з сервісу відеохостингу (Youtube)
> - [x] Формування цін
> - [x] Категоризація інвентару

ДОСЛІДИТИ ТЕХНОЛОГІЇ:

> - [x] Html (для розмітки сторінки)
> - [x] Scss (для стилізації сторінки)
> - [x] JavaScript (для розширення функціоналу вебсайту)

**Comment by AlexanderZero435** [comment]
> - [x ] Дослідити можливості та обмеження Github Pages (https://docs.github.com/en/pages)
